# Code generated by scripts/generate-bindings.py from bindings/api.json; DO NOT EDIT.
"""Stable liblevenshtein native ABI generation."""
const ABI_VERSION = UInt32(1)
"""Minimum additive native API revision required by this facade."""
const API_REVISION = UInt32(4)
"""Default maximum number of match descriptors per native batch."""
const DEFAULT_MATCH_BATCH = 256
"""Compiled native feature bit: core."""
const BUILD_FEATURE_CORE = UInt64(1)
"""Compiled native feature bit: phonetic."""
const BUILD_FEATURE_PHONETIC = UInt64(2)

"""Result of a fallible native operation."""
@enum Status::Cint begin
    STATUS_OK = 0
    STATUS_END = 1
    STATUS_INVALID_ARGUMENT = 2
    STATUS_INVALID_UTF8 = 3
    STATUS_NULL_POINTER = 4
    STATUS_PANIC = 5
    STATUS_UNSUPPORTED = 6
    STATUS_IO_ERROR = 7
    STATUS_CLOSED = 8
    STATUS_LIMIT_EXCEEDED = 9
    STATUS_PROVIDER_ERROR = 10
    STATUS_BATCH_IN_USE = 11
    STATUS_DOMAIN_MISMATCH = 12
end

"""Edit-distance algorithm."""
@enum Algorithm::UInt32 begin
    ALGORITHM_STANDARD = 0
    ALGORITHM_TRANSPOSITION = 1
    ALGORITHM_MERGE_AND_SPLIT = 2
    ALGORITHM_DAMERAU_LEVENSHTEIN = 3
end

"""Lazy result ordering."""
@enum QueryOrder::UInt32 begin
    ORDER_TRAVERSAL = 0
    ORDER_DISTANCE_THEN_TERM = 1
end

"""Built-in phonetic rewrite-rule set."""
@enum PhoneticRuleSetKind::UInt32 begin
    RULES_ENGLISH_ORTHOGRAPHY = 0
    RULES_ENGLISH_PHONETIC = 1
end
