// Code generated by scripts/generate-bindings.py from bindings/api.json; DO NOT EDIT.

/// Result of a fallible native operation.
///
/// This is an open raw-value wrapper so statuses introduced by a newer
/// compatible API revision remain observable rather than being discarded.
public struct Status: RawRepresentable, Hashable, Sendable, CustomStringConvertible {
    public let rawValue: UInt32

    public init(rawValue: UInt32) { self.rawValue = rawValue }

    /// The operation completed successfully.
    public static let ok = Status(rawValue: 0)
    /// A finite cursor reached the end of its stream.
    public static let end = Status(rawValue: 1)
    /// An argument violated the operation's contract.
    public static let invalidArgument = Status(rawValue: 2)
    /// Input advertised as text was not valid UTF-8.
    public static let invalidUtf8 = Status(rawValue: 3)
    /// A required native pointer was null.
    public static let nullPointer = Status(rawValue: 4)
    /// A contained Rust panic crossed the failure boundary.
    public static let panic = Status(rawValue: 5)
    /// The requested capability is unavailable in this build.
    public static let unsupported = Status(rawValue: 6)
    /// An input/output operation failed.
    public static let ioError = Status(rawValue: 7)
    /// The target resource was already closed.
    public static let closed = Status(rawValue: 8)
    /// A configured resource or traversal limit was exceeded.
    public static let limitExceeded = Status(rawValue: 9)
    /// A foreign dictionary provider reported a failure.
    public static let providerError = Status(rawValue: 10)
    /// A cursor was advanced while its previous batch remained borrowed.
    public static let batchInUse = Status(rawValue: 11)
    /// The query and dictionary use different unit domains.
    public static let domainMismatch = Status(rawValue: 12)

    public var description: String {
        switch self {
        case .ok: "OK"
        case .end: "END"
        case .invalidArgument: "INVALID_ARGUMENT"
        case .invalidUtf8: "INVALID_UTF8"
        case .nullPointer: "NULL_POINTER"
        case .panic: "PANIC"
        case .unsupported: "UNSUPPORTED"
        case .ioError: "IO_ERROR"
        case .closed: "CLOSED"
        case .limitExceeded: "LIMIT_EXCEEDED"
        case .providerError: "PROVIDER_ERROR"
        case .batchInUse: "BATCH_IN_USE"
        case .domainMismatch: "DOMAIN_MISMATCH"
        default: "UNKNOWN(\(rawValue))"
        }
    }
}

/// Edit-distance algorithm.
public enum Algorithm: UInt32, Sendable {
    /// Standard insert/delete/substitute distance.
    case standard = 0
    /// Optimal string alignment with adjacent transposition.
    case transposition = 1
    /// Merge-and-split edit distance.
    case mergeAndSplit = 2
    /// Unrestricted Damerau-Levenshtein distance.
    case damerauLevenshtein = 3
}

/// Lazy result ordering.
public enum QueryOrder: UInt32, Sendable {
    /// Provider traversal order with bounded buffering.
    case traversal = 0
    /// Distance then term, buffering at most one distance layer.
    case distanceThenTerm = 1
}

/// Built-in phonetic rewrite-rule set.
public enum PhoneticRuleSetKind: UInt32, Sendable {
    /// English orthography normalization.
    case englishOrthography = 0
    /// English phonetic transformation.
    case englishPhonetic = 1
}
