// Code generated by scripts/generate-bindings.py from bindings/api.json; DO NOT EDIT.

package liblevenshtein

// Status is the result of a fallible native operation.
type Status uint32

const (
	// StatusOK indicates the operation completed successfully.
	StatusOK Status = 0
	// StatusEnd indicates a finite cursor reached the end of its stream.
	StatusEnd Status = 1
	// StatusInvalidArgument indicates an argument violated the operation's contract.
	StatusInvalidArgument Status = 2
	// StatusInvalidUTF8 indicates input advertised as text was not valid UTF-8.
	StatusInvalidUTF8 Status = 3
	// StatusNullPointer indicates a required native pointer was null.
	StatusNullPointer Status = 4
	// StatusPanic indicates a contained Rust panic crossed the failure boundary.
	StatusPanic Status = 5
	// StatusUnsupported indicates the requested capability is unavailable in this build.
	StatusUnsupported Status = 6
	// StatusIOError indicates an input/output operation failed.
	StatusIOError Status = 7
	// StatusClosed indicates the target resource was already closed.
	StatusClosed Status = 8
	// StatusLimitExceeded indicates a configured resource or traversal limit was exceeded.
	StatusLimitExceeded Status = 9
	// StatusProviderError indicates a foreign dictionary provider reported a failure.
	StatusProviderError Status = 10
	// StatusBatchInUse indicates a cursor was advanced while its previous batch remained borrowed.
	StatusBatchInUse Status = 11
	// StatusDomainMismatch indicates the query and dictionary use different unit domains.
	StatusDomainMismatch Status = 12
)

// Algorithm is the edit-distance algorithm.
type Algorithm uint32

const (
	// Standard indicates standard insert/delete/substitute distance.
	Standard Algorithm = 0
	// Transposition indicates optimal string alignment with adjacent transposition.
	Transposition Algorithm = 1
	// MergeAndSplit indicates merge-and-split edit distance.
	MergeAndSplit Algorithm = 2
	// DamerauLevenshtein indicates unrestricted Damerau-Levenshtein distance.
	DamerauLevenshtein Algorithm = 3
)

// QueryOrder is the lazy result ordering.
type QueryOrder uint32

const (
	// Traversal indicates provider traversal order with bounded buffering.
	Traversal QueryOrder = 0
	// DistanceThenTerm indicates distance then term, buffering at most one distance layer.
	DistanceThenTerm QueryOrder = 1
)

// PhoneticRuleSetKind is the built-in phonetic rewrite-rule set.
type PhoneticRuleSetKind uint32

const (
	// EnglishOrthography indicates english orthography normalization.
	EnglishOrthography PhoneticRuleSetKind = 0
	// EnglishPhonetic indicates english phonetic transformation.
	EnglishPhonetic PhoneticRuleSetKind = 1
)
