unit module Liblevenshtein::GeneratedAbi;

# Code generated by scripts/generate-bindings.py from bindings/api.json; DO NOT EDIT.
our constant ABI-VERSION is export = 1;
our constant API-REVISION is export = 3;
our constant DEFAULT-MATCH-BATCH is export = 256;
our constant BUILD-FEATURE-CORE is export = 1;
our constant BUILD-FEATURE-PHONETIC is export = 2;

our enum Status is export (
    OK => 0,
    END => 1,
    INVALID-ARGUMENT => 2,
    INVALID-UTF8 => 3,
    NULL-POINTER => 4,
    PANIC => 5,
    UNSUPPORTED => 6,
    IO-ERROR => 7,
    CLOSED => 8,
    LIMIT-EXCEEDED => 9,
    PROVIDER-ERROR => 10,
    BATCH-IN-USE => 11,
    DOMAIN-MISMATCH => 12,
);

our enum Algorithm is export (
    STANDARD => 0,
    TRANSPOSITION => 1,
    MERGE-AND-SPLIT => 2,
    DAMERAU-LEVENSHTEIN => 3,
);

our enum QueryOrder is export (
    TRAVERSAL => 0,
    DISTANCE-THEN-TERM => 1,
);

our enum PhoneticRuleSetKind is export (
    ENGLISH-ORTHOGRAPHY => 0,
    ENGLISH-PHONETIC => 1,
);
