// <auto-generated />
// Generated from bindings/api.json; do not edit numeric values manually.

namespace VinaryTree.Liblevenshtein;

/// <summary>
/// Result of a fallible native operation. The uint backing value preserves statuses introduced by a newer compatible API revision.
/// </summary>
public enum Status : uint
{
    /// <summary>The operation completed successfully.</summary>
    Ok = 0,
    /// <summary>A finite cursor reached the end of its stream.</summary>
    End = 1,
    /// <summary>An argument violated the operation's contract.</summary>
    InvalidArgument = 2,
    /// <summary>Input advertised as text was not valid UTF-8.</summary>
    InvalidUtf8 = 3,
    /// <summary>A required native pointer was null.</summary>
    NullPointer = 4,
    /// <summary>A contained Rust panic crossed the failure boundary.</summary>
    Panic = 5,
    /// <summary>The requested capability is unavailable in this build.</summary>
    Unsupported = 6,
    /// <summary>An input/output operation failed.</summary>
    IoError = 7,
    /// <summary>The target resource was already closed.</summary>
    Closed = 8,
    /// <summary>A configured resource or traversal limit was exceeded.</summary>
    LimitExceeded = 9,
    /// <summary>A foreign dictionary provider reported a failure.</summary>
    ProviderError = 10,
    /// <summary>A cursor was advanced while its previous batch remained borrowed.</summary>
    BatchInUse = 11,
    /// <summary>The query and dictionary use different unit domains.</summary>
    DomainMismatch = 12,
}

/// <summary>
/// Edit-distance algorithm.
/// </summary>
public enum Algorithm : uint
{
    /// <summary>Standard insert/delete/substitute distance.</summary>
    Standard = 0,
    /// <summary>Optimal string alignment with adjacent transposition.</summary>
    Transposition = 1,
    /// <summary>Merge-and-split edit distance.</summary>
    MergeAndSplit = 2,
    /// <summary>Unrestricted Damerau-Levenshtein distance.</summary>
    DamerauLevenshtein = 3,
}

/// <summary>
/// Lazy result ordering.
/// </summary>
public enum QueryOrder : uint
{
    /// <summary>Provider traversal order with bounded buffering.</summary>
    Traversal = 0,
    /// <summary>Distance then term, buffering at most one distance layer.</summary>
    DistanceThenTerm = 1,
}

/// <summary>
/// Built-in phonetic rewrite-rule set.
/// </summary>
public enum PhoneticRuleSetKind : uint
{
    /// <summary>English orthography normalization.</summary>
    EnglishOrthography = 0,
    /// <summary>English phonetic transformation.</summary>
    EnglishPhonetic = 1,
}

/// <summary>
/// Runtime generalized-operation applicability predicate.
/// </summary>
public enum OperationApplicability : uint
{
    /// <summary>Apply without inspecting consumed units.</summary>
    Any = 0,
    /// <summary>Apply only when the consumed source and target slices are equal.</summary>
    Equal = 1,
    /// <summary>Apply only to an adjacent two-unit transposition.</summary>
    AdjacentTranspose = 2,
    /// <summary>Apply only to a configured directional source/target pair.</summary>
    Listed = 3,
}

/// <summary>
/// Universal edit-automaton variant.
/// </summary>
public enum UniversalVariant : uint
{
    /// <summary>Standard insert/delete/substitute universal automaton.</summary>
    Standard = 0,
    /// <summary>Universal automaton with adjacent transposition.</summary>
    Transposition = 1,
    /// <summary>Universal automaton with merge-and-split edits.</summary>
    MergeAndSplit = 2,
}
