# frozen_string_literal: true

# Code generated by scripts/generate-bindings.py from bindings/api.json; DO NOT EDIT.
module VinaryTree
  module Liblevenshtein
    module Status
      OK = 0
      END_OF_STREAM = 1
      INVALID_ARGUMENT = 2
      INVALID_UTF8 = 3
      NULL_POINTER = 4
      PANIC = 5
      UNSUPPORTED = 6
      IO_ERROR = 7
      CLOSED = 8
      LIMIT_EXCEEDED = 9
      PROVIDER_ERROR = 10
      BATCH_IN_USE = 11
      DOMAIN_MISMATCH = 12
    end

    module Algorithm
      STANDARD = 0
      TRANSPOSITION = 1
      MERGE_AND_SPLIT = 2
      DAMERAU_LEVENSHTEIN = 3
    end

    module QueryOrder
      TRAVERSAL = 0
      DISTANCE_THEN_TERM = 1
    end

    module PhoneticRuleSetKind
      ENGLISH_ORTHOGRAPHY = 0
      ENGLISH_PHONETIC = 1
    end

    module OperationApplicability
      ANY = 0
      EQUAL = 1
      ADJACENT_TRANSPOSE = 2
      LISTED = 3
    end

    module UniversalVariant
      STANDARD = 0
      TRANSPOSITION = 1
      MERGE_AND_SPLIT = 2
    end

  end
end
