# frozen_string_literal: true

# Code generated by scripts/generate-bindings.py from bindings/api.json; DO NOT EDIT.
# Vinary Tree's versioned native selections. Use the named values rather than
# depending on their integer representation across API revisions.
module VinaryTree
  module Liblevenshtein
    # Result of a fallible native operation.
    module Status
      # The operation completed successfully.
      OK = 0
      # A finite cursor reached the end of its stream.
      END_OF_STREAM = 1
      # An argument violated the operation's contract.
      INVALID_ARGUMENT = 2
      # Input advertised as text was not valid UTF-8.
      INVALID_UTF8 = 3
      # A required native pointer was null.
      NULL_POINTER = 4
      # A contained Rust panic crossed the failure boundary.
      PANIC = 5
      # The requested capability is unavailable in this build.
      UNSUPPORTED = 6
      # An input/output operation failed.
      IO_ERROR = 7
      # The target resource was already closed.
      CLOSED = 8
      # A configured resource or traversal limit was exceeded.
      LIMIT_EXCEEDED = 9
      # A foreign dictionary provider reported a failure.
      PROVIDER_ERROR = 10
      # A cursor was advanced while its previous batch remained borrowed.
      BATCH_IN_USE = 11
      # The query and dictionary use different unit domains.
      DOMAIN_MISMATCH = 12
    end

    # Edit-distance algorithm.
    module Algorithm
      # Standard insert/delete/substitute distance.
      STANDARD = 0
      # Optimal string alignment with adjacent transposition.
      TRANSPOSITION = 1
      # Merge-and-split edit distance.
      MERGE_AND_SPLIT = 2
      # Unrestricted Damerau-Levenshtein distance.
      DAMERAU_LEVENSHTEIN = 3
    end

    # Lazy result ordering.
    module QueryOrder
      # Provider traversal order with bounded buffering.
      TRAVERSAL = 0
      # Distance then term, buffering at most one distance layer.
      DISTANCE_THEN_TERM = 1
    end

    # Built-in phonetic rewrite-rule set.
    module PhoneticRuleSetKind
      # English orthography normalization.
      ENGLISH_ORTHOGRAPHY = 0
      # English phonetic transformation.
      ENGLISH_PHONETIC = 1
    end

    # Runtime generalized-operation applicability predicate.
    module OperationApplicability
      # Apply without inspecting consumed units.
      ANY = 0
      # Apply only when the consumed source and target slices are equal.
      EQUAL = 1
      # Apply only to an adjacent two-unit transposition.
      ADJACENT_TRANSPOSE = 2
      # Apply only to a configured directional source/target pair.
      LISTED = 3
    end

    # Universal edit-automaton variant.
    module UniversalVariant
      # Standard insert/delete/substitute universal automaton.
      STANDARD = 0
      # Universal automaton with adjacent transposition.
      TRANSPOSITION = 1
      # Universal automaton with merge-and-split edits.
      MERGE_AND_SPLIT = 2
    end

  end
end
