name = "liblevenshtein"
version = "4.0.0"
license = "Apache-2.0"
author = "Dylon Edwards"
maintainer = "Dylon Edwards <dylon.devo@gmail.com>"
description = "A high-performance library for spelling correction, fuzzy dictionary search, and phonetic matching using Levenshtein and related finite-state automata."

[library]
source-dir = "src"

[dependencies]
vinary-tree-interop = { path = "../../../vinary-tree-interop/bindings/fortran" }

[build]
link = ["liblevenshtein"]
module-naming = false
