name = "liblevenshtein"
version = "4.0.0"
license = "Apache-2.0"
author = "Dylon Edwards"
maintainer = "Dylon Edwards <dylon.devo@gmail.com>"
description = "Snapshot-consistent streaming Levenshtein search"
homepage = "https://github.com/vinary-tree/liblevenshtein-rust"

[library]
source-dir = "src"

[dependencies.vinary-tree-interop]
namespace = "vinary-tree"
v = "4.0.0"

[build]
link = ["liblevenshtein"]
module-naming = true
