//! Feature-gated counters for causal performance investigations.
//!
//! The hot path calls the recording functions unconditionally. Without the
//! `perf-instrumentation` feature they inline to no-ops, so ordinary builds do
//! not contain counters or branches. Instrumented builds use relaxed atomics:
//! the counters are observations, never synchronization inputs.

#![allow(dead_code)]

#[cfg(feature = "perf-instrumentation")]
use std::sync::atomic::{AtomicU64, Ordering};

/// Logical work performed by dictionary traversal and automaton simulation.
///
/// Timing and work counters must be collected in separate runs because the
/// instrumented hot path intentionally favors complete observability over
/// minimum overhead.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct CausalPerfStats {
    /// Dictionary/automaton intersections removed from a pending queue.
    pub dictionary_intersections: u64,
    /// Owned dictionary-node handles inserted into the compatibility arena.
    pub owned_traversal_arena_insertions: u64,
    /// Dictionary-node finality checks.
    pub final_checks: u64,
    /// Outgoing dictionary edges enumerated.
    pub edges_enumerated: u64,
    /// Automaton transitions attempted for dictionary edges.
    pub transition_attempts: u64,
    /// Automaton transitions that produced a non-empty state.
    pub transition_accepted: u64,
    /// Queries represented by the one-word Standard transition machine.
    pub packed_standard_queries: u64,
    /// Queries routed to the positional transition fallback.
    pub positional_unit_queries: u64,
    /// Dictionary-edge transitions attempted by the packed Standard machine.
    pub packed_standard_transition_attempts: u64,
    /// Packed Standard transitions whose bounded frontier became empty.
    pub packed_standard_transition_dead: u64,
    /// Queries represented by the two-plane packed OSA machine.
    pub packed_osa_queries: u64,
    /// OSA queries kept positional because their policy may equate distinct units.
    pub packed_osa_fallback_policy: u64,
    /// OSA queries kept positional because prefix semantics were requested.
    pub packed_osa_fallback_prefix: u64,
    /// OSA queries kept positional because their frontier exceeded two words.
    pub packed_osa_fallback_width: u64,
    /// Dictionary-edge transitions attempted by the packed OSA machine.
    pub packed_osa_transition_attempts: u64,
    /// Packed OSA transitions whose bounded frontier became empty.
    pub packed_osa_transition_dead: u64,
    /// Queries represented by the two-plane packed MergeSplit machine.
    pub packed_merge_split_queries: u64,
    /// MergeSplit queries kept positional because their policy may equate distinct units.
    pub packed_merge_split_fallback_policy: u64,
    /// MergeSplit queries kept positional because prefix semantics were requested.
    pub packed_merge_split_fallback_prefix: u64,
    /// MergeSplit queries kept positional because their frontier exceeded two words.
    pub packed_merge_split_fallback_width: u64,
    /// Dictionary-edge transitions attempted by the packed MergeSplit machine.
    pub packed_merge_split_transition_attempts: u64,
    /// Packed MergeSplit transitions whose bounded frontier became empty.
    pub packed_merge_split_transition_dead: u64,
    /// Eligible exact-match queries represented by dense packed-DFA states.
    pub packed_dfa_queries: u64,
    /// Packed-DFA transitions served from an already generated row cell.
    pub packed_dfa_transition_hits: u64,
    /// Packed-DFA row cells that required one bounded-NFA recurrence.
    pub packed_dfa_transition_misses: u64,
    /// Distinct packed frontiers interned as dense DFA state identifiers.
    pub packed_dfa_states_interned: u64,
    /// Source-fixed packed-DFA rows prepared for dictionary-node expansions.
    pub packed_dfa_source_rows_prepared: u64,
    /// Source-row labels mapped to class zero (absent from the query).
    pub packed_dfa_class_zero_probes: u64,
    /// Class-zero probes after the first such probe in the same expansion.
    pub packed_dfa_class_zero_reusable_probes: u64,
    /// Physical loads from the packed-DFA target table.
    pub packed_dfa_physical_target_probes: u64,
    /// Transitions replayed from the query-local generated state table.
    pub generated_transition_hits: u64,
    /// Transitions generated by the positional reference kernel.
    pub generated_transition_misses: u64,
    /// Unit-cost dictionary/product nodes expanded by query traversal.
    pub generated_product_expansions: u64,
    /// Product expansions whose dictionary node exposes stable identity.
    pub generated_product_identity_expansions: u64,
    /// Distinct `(dictionary node, generated state)` products expanded.
    pub generated_product_unique_expansions: u64,
    /// Repeated expansions of a previously observed stable product.
    pub generated_product_repeated_expansions: u64,
    /// Positions entering epsilon-closure computations.
    pub epsilon_input_positions: u64,
    /// Positions produced by epsilon-closure computations.
    pub epsilon_output_positions: u64,
    /// Characteristic vectors constructed.
    pub characteristic_vectors: u64,
    /// Query units inspected while constructing characteristic vectors.
    pub characteristic_units: u64,
    /// Successor positions produced before state subsumption.
    pub successor_candidates: u64,
    /// State-position insertions attempted.
    pub state_insert_attempts: u64,
    /// State-position insertions retained after subsumption.
    pub state_insert_retained: u64,
    /// Pairwise dominance checks performed by online subsumption.
    pub subsumption_checks: u64,
    /// Calls that copied one complete automaton state.
    pub state_copy_calls: u64,
    /// Positions copied by complete-state copies.
    pub state_positions_copied: u64,
    /// Bytes copied by complete-state copies.
    pub state_bytes_copied: u64,
    /// Positions embedded in accepted pending intersections.
    pub state_positions_enqueued: u64,
    /// Position bytes embedded in accepted pending intersections.
    pub state_bytes_enqueued: u64,
    /// Maximum number of pending intersections observed.
    pub pending_queue_peak: u64,
    /// State-pool acquisitions.
    pub pool_acquires: u64,
    /// State-pool acquisitions satisfied by a recycled state.
    pub pool_reuses: u64,
    /// State-pool acquisitions that created a new state.
    pub pool_misses: u64,
    /// States returned to the pool.
    pub pool_releases: u64,
    /// Accepted matches materialized by native query iterators.
    pub matches_materialized: u64,
    /// Queries retaining the generic parent-path arena.
    pub parent_path_queries: u64,
    /// Queries using cursor-native key reconstruction.
    pub cursor_key_queries: u64,
    /// Parent-path nodes created for accepted traversal branches.
    pub path_arena_nodes_created: u64,
    /// Accepted keys reconstructed from immutable backend cursors.
    pub cursor_key_reconstructions: u64,
    /// CHECK-parent steps walked during cursor-key reconstruction.
    pub cursor_key_reverse_steps: u64,
    /// Root-relative term units materialized across both path strategies.
    pub term_units_materialized: u64,
    /// DFS nodes opened with bounded lazy edge paging.
    pub dfs_nodes_paged: u64,
    /// DFS nodes expanded eagerly for compatibility or causal control.
    pub dfs_nodes_eager: u64,
    /// Physical edge-page refills requested by DFS iterators.
    pub dfs_edge_page_requests: u64,
    /// Edge descriptors copied into bounded DFS pages or eager buffers.
    pub dfs_edges_fetched: u64,
    /// Buffered edges actually presented to DFS query semantics.
    pub dfs_edges_consumed: u64,
    /// Maximum number of descriptors retained in one bounded DFS page.
    pub dfs_edge_buffer_peak: u64,
    /// DFS page refills that exceeded the inline descriptor capacity.
    pub dfs_edge_buffer_spills: u64,
    /// Foreign-provider finality callbacks.
    pub foreign_is_final_callbacks: u64,
    /// Foreign-provider edge callbacks.
    pub foreign_edge_callbacks: u64,
    /// Edge pages allocated and submitted to a foreign provider.
    pub foreign_edge_pages: u64,
    /// Foreign edge descriptors accepted and copied into consumer nodes.
    pub foreign_edge_descriptors: u64,
    /// Immutable foreign nodes served from the consumer snapshot cache.
    pub foreign_node_cache_hits: u64,
    /// Immutable foreign nodes populated into the consumer snapshot cache.
    pub foreign_node_cache_misses: u64,
    /// Snapshot traversal cursors emitted with a pending cache-entry target.
    pub foreign_pending_cursors_emitted: u64,
    /// Snapshot traversal cursors emitted with a direct ready descriptor.
    pub foreign_ready_cursors_emitted: u64,
    /// Child-edge targets promoted monotonically from pending to ready.
    pub foreign_edge_cursor_promotions: u64,
    /// Acquire loads of a pending entry's descriptor publication cell.
    pub foreign_pending_descriptor_loads: u64,
    /// Node inspections served directly from a ready descriptor target.
    pub foreign_ready_descriptor_reads: u64,
    /// Canonical child-entry directory lookups performed on empty edge slots.
    pub foreign_child_directory_lookups: u64,
    /// Expanded immutable foreign nodes whose cached edge slice is empty.
    pub foreign_leaf_expansions: u64,
    /// Compact foreign graphs decoded and validated into native traversal storage.
    pub foreign_graph_decodes: u64,
    /// Matches copied into C ABI views.
    pub ffi_matches_packed: u64,
    /// Term bytes copied into C ABI arenas.
    pub ffi_bytes_packed: u64,
}

#[cfg(feature = "perf-instrumentation")]
macro_rules! counter {
    ($name:ident) => {
        static $name: AtomicU64 = AtomicU64::new(0);
    };
}

#[cfg(feature = "perf-instrumentation")]
counter!(DICTIONARY_INTERSECTIONS);
#[cfg(feature = "perf-instrumentation")]
counter!(OWNED_TRAVERSAL_ARENA_INSERTIONS);
#[cfg(feature = "perf-instrumentation")]
counter!(FINAL_CHECKS);
#[cfg(feature = "perf-instrumentation")]
counter!(EDGES_ENUMERATED);
#[cfg(feature = "perf-instrumentation")]
counter!(TRANSITION_ATTEMPTS);
#[cfg(feature = "perf-instrumentation")]
counter!(TRANSITION_ACCEPTED);
#[cfg(feature = "perf-instrumentation")]
counter!(PACKED_STANDARD_QUERIES);
#[cfg(feature = "perf-instrumentation")]
counter!(POSITIONAL_UNIT_QUERIES);
#[cfg(feature = "perf-instrumentation")]
counter!(PACKED_STANDARD_TRANSITION_ATTEMPTS);
#[cfg(feature = "perf-instrumentation")]
counter!(PACKED_STANDARD_TRANSITION_DEAD);
#[cfg(feature = "perf-instrumentation")]
counter!(PACKED_OSA_QUERIES);
#[cfg(feature = "perf-instrumentation")]
counter!(PACKED_OSA_FALLBACK_POLICY);
#[cfg(feature = "perf-instrumentation")]
counter!(PACKED_OSA_FALLBACK_PREFIX);
#[cfg(feature = "perf-instrumentation")]
counter!(PACKED_OSA_FALLBACK_WIDTH);
#[cfg(feature = "perf-instrumentation")]
counter!(PACKED_OSA_TRANSITION_ATTEMPTS);
#[cfg(feature = "perf-instrumentation")]
counter!(PACKED_OSA_TRANSITION_DEAD);
#[cfg(feature = "perf-instrumentation")]
counter!(PACKED_MERGE_SPLIT_QUERIES);
#[cfg(feature = "perf-instrumentation")]
counter!(PACKED_MERGE_SPLIT_FALLBACK_POLICY);
#[cfg(feature = "perf-instrumentation")]
counter!(PACKED_MERGE_SPLIT_FALLBACK_PREFIX);
#[cfg(feature = "perf-instrumentation")]
counter!(PACKED_MERGE_SPLIT_FALLBACK_WIDTH);
#[cfg(feature = "perf-instrumentation")]
counter!(PACKED_MERGE_SPLIT_TRANSITION_ATTEMPTS);
#[cfg(feature = "perf-instrumentation")]
counter!(PACKED_MERGE_SPLIT_TRANSITION_DEAD);
#[cfg(feature = "perf-instrumentation")]
counter!(PACKED_DFA_QUERIES);
#[cfg(feature = "perf-instrumentation")]
counter!(PACKED_DFA_TRANSITION_HITS);
#[cfg(feature = "perf-instrumentation")]
counter!(PACKED_DFA_TRANSITION_MISSES);
#[cfg(feature = "perf-instrumentation")]
counter!(PACKED_DFA_STATES_INTERNED);
#[cfg(feature = "perf-instrumentation")]
counter!(PACKED_DFA_SOURCE_ROWS_PREPARED);
#[cfg(feature = "perf-instrumentation")]
counter!(PACKED_DFA_CLASS_ZERO_PROBES);
#[cfg(feature = "perf-instrumentation")]
counter!(PACKED_DFA_CLASS_ZERO_REUSABLE_PROBES);
#[cfg(feature = "perf-instrumentation")]
counter!(PACKED_DFA_PHYSICAL_TARGET_PROBES);
#[cfg(feature = "perf-instrumentation")]
counter!(GENERATED_TRANSITION_HITS);
#[cfg(feature = "perf-instrumentation")]
counter!(GENERATED_TRANSITION_MISSES);
#[cfg(feature = "perf-instrumentation")]
counter!(GENERATED_PRODUCT_EXPANSIONS);
#[cfg(feature = "perf-instrumentation")]
counter!(GENERATED_PRODUCT_IDENTITY_EXPANSIONS);
#[cfg(feature = "perf-instrumentation")]
counter!(GENERATED_PRODUCT_UNIQUE_EXPANSIONS);
#[cfg(feature = "perf-instrumentation")]
counter!(GENERATED_PRODUCT_REPEATED_EXPANSIONS);
#[cfg(feature = "perf-instrumentation")]
counter!(EPSILON_INPUT_POSITIONS);
#[cfg(feature = "perf-instrumentation")]
counter!(EPSILON_OUTPUT_POSITIONS);
#[cfg(feature = "perf-instrumentation")]
counter!(CHARACTERISTIC_VECTORS);
#[cfg(feature = "perf-instrumentation")]
counter!(CHARACTERISTIC_UNITS);
#[cfg(feature = "perf-instrumentation")]
counter!(SUCCESSOR_CANDIDATES);
#[cfg(feature = "perf-instrumentation")]
counter!(STATE_INSERT_ATTEMPTS);
#[cfg(feature = "perf-instrumentation")]
counter!(STATE_INSERT_RETAINED);
#[cfg(feature = "perf-instrumentation")]
counter!(SUBSUMPTION_CHECKS);
#[cfg(feature = "perf-instrumentation")]
counter!(STATE_COPY_CALLS);
#[cfg(feature = "perf-instrumentation")]
counter!(STATE_POSITIONS_COPIED);
#[cfg(feature = "perf-instrumentation")]
counter!(STATE_BYTES_COPIED);
#[cfg(feature = "perf-instrumentation")]
counter!(STATE_POSITIONS_ENQUEUED);
#[cfg(feature = "perf-instrumentation")]
counter!(STATE_BYTES_ENQUEUED);
#[cfg(feature = "perf-instrumentation")]
counter!(PENDING_QUEUE_PEAK);
#[cfg(feature = "perf-instrumentation")]
counter!(POOL_ACQUIRES);
#[cfg(feature = "perf-instrumentation")]
counter!(POOL_REUSES);
#[cfg(feature = "perf-instrumentation")]
counter!(POOL_MISSES);
#[cfg(feature = "perf-instrumentation")]
counter!(POOL_RELEASES);
#[cfg(feature = "perf-instrumentation")]
counter!(MATCHES_MATERIALIZED);
#[cfg(feature = "perf-instrumentation")]
counter!(PARENT_PATH_QUERIES);
#[cfg(feature = "perf-instrumentation")]
counter!(CURSOR_KEY_QUERIES);
#[cfg(feature = "perf-instrumentation")]
counter!(PATH_ARENA_NODES_CREATED);
#[cfg(feature = "perf-instrumentation")]
counter!(CURSOR_KEY_RECONSTRUCTIONS);
#[cfg(feature = "perf-instrumentation")]
counter!(CURSOR_KEY_REVERSE_STEPS);
#[cfg(feature = "perf-instrumentation")]
counter!(TERM_UNITS_MATERIALIZED);
#[cfg(feature = "perf-instrumentation")]
counter!(DFS_NODES_PAGED);
#[cfg(feature = "perf-instrumentation")]
counter!(DFS_NODES_EAGER);
#[cfg(feature = "perf-instrumentation")]
counter!(DFS_EDGE_PAGE_REQUESTS);
#[cfg(feature = "perf-instrumentation")]
counter!(DFS_EDGES_FETCHED);
#[cfg(feature = "perf-instrumentation")]
counter!(DFS_EDGES_CONSUMED);
#[cfg(feature = "perf-instrumentation")]
counter!(DFS_EDGE_BUFFER_PEAK);
#[cfg(feature = "perf-instrumentation")]
counter!(DFS_EDGE_BUFFER_SPILLS);
#[cfg(feature = "perf-instrumentation")]
counter!(FOREIGN_IS_FINAL_CALLBACKS);
#[cfg(feature = "perf-instrumentation")]
counter!(FOREIGN_EDGE_CALLBACKS);
#[cfg(feature = "perf-instrumentation")]
counter!(FOREIGN_EDGE_PAGES);
#[cfg(feature = "perf-instrumentation")]
counter!(FOREIGN_EDGE_DESCRIPTORS);
#[cfg(feature = "perf-instrumentation")]
counter!(FOREIGN_NODE_CACHE_HITS);
#[cfg(feature = "perf-instrumentation")]
counter!(FOREIGN_NODE_CACHE_MISSES);
#[cfg(feature = "perf-instrumentation")]
counter!(FOREIGN_PENDING_CURSORS_EMITTED);
#[cfg(feature = "perf-instrumentation")]
counter!(FOREIGN_READY_CURSORS_EMITTED);
#[cfg(feature = "perf-instrumentation")]
counter!(FOREIGN_EDGE_CURSOR_PROMOTIONS);
#[cfg(feature = "perf-instrumentation")]
counter!(FOREIGN_PENDING_DESCRIPTOR_LOADS);
#[cfg(feature = "perf-instrumentation")]
counter!(FOREIGN_READY_DESCRIPTOR_READS);
#[cfg(feature = "perf-instrumentation")]
counter!(FOREIGN_CHILD_DIRECTORY_LOOKUPS);
#[cfg(feature = "perf-instrumentation")]
counter!(FOREIGN_LEAF_EXPANSIONS);
#[cfg(feature = "perf-instrumentation")]
counter!(FOREIGN_GRAPH_DECODES);
#[cfg(feature = "perf-instrumentation")]
counter!(FFI_MATCHES_PACKED);
#[cfg(feature = "perf-instrumentation")]
counter!(FFI_BYTES_PACKED);

#[inline(always)]
fn add(counter: &Counter, value: u64) {
    counter.add(value);
}

#[cfg(feature = "perf-instrumentation")]
struct Counter(&'static AtomicU64);

#[cfg(feature = "perf-instrumentation")]
impl Counter {
    #[inline(always)]
    fn add(&self, value: u64) {
        self.0.fetch_add(value, Ordering::Relaxed);
    }
}

#[cfg(not(feature = "perf-instrumentation"))]
struct Counter;

#[cfg(not(feature = "perf-instrumentation"))]
impl Counter {
    #[inline(always)]
    fn add(&self, _value: u64) {}
}

macro_rules! recorder {
    ($function:ident, $counter:ident) => {
        #[inline(always)]
        pub(crate) fn $function(value: u64) {
            #[cfg(feature = "perf-instrumentation")]
            add(&Counter(&$counter), value);
            #[cfg(not(feature = "perf-instrumentation"))]
            add(&Counter, value);
        }
    };
}

recorder!(record_dictionary_intersections, DICTIONARY_INTERSECTIONS);
recorder!(
    record_owned_traversal_arena_insertions,
    OWNED_TRAVERSAL_ARENA_INSERTIONS
);
recorder!(record_final_checks, FINAL_CHECKS);
recorder!(record_edges_enumerated, EDGES_ENUMERATED);
recorder!(record_transition_attempts, TRANSITION_ATTEMPTS);
recorder!(record_transition_accepted, TRANSITION_ACCEPTED);
recorder!(record_packed_standard_queries, PACKED_STANDARD_QUERIES);
recorder!(record_positional_unit_queries, POSITIONAL_UNIT_QUERIES);
recorder!(
    record_packed_standard_transition_attempts,
    PACKED_STANDARD_TRANSITION_ATTEMPTS
);
recorder!(
    record_packed_standard_transition_dead,
    PACKED_STANDARD_TRANSITION_DEAD
);
recorder!(record_packed_osa_queries, PACKED_OSA_QUERIES);
recorder!(
    record_packed_osa_fallback_policy,
    PACKED_OSA_FALLBACK_POLICY
);
recorder!(
    record_packed_osa_fallback_prefix,
    PACKED_OSA_FALLBACK_PREFIX
);
recorder!(record_packed_osa_fallback_width, PACKED_OSA_FALLBACK_WIDTH);
recorder!(
    record_packed_osa_transition_attempts,
    PACKED_OSA_TRANSITION_ATTEMPTS
);
recorder!(
    record_packed_osa_transition_dead,
    PACKED_OSA_TRANSITION_DEAD
);
recorder!(
    record_packed_merge_split_queries,
    PACKED_MERGE_SPLIT_QUERIES
);
recorder!(
    record_packed_merge_split_fallback_policy,
    PACKED_MERGE_SPLIT_FALLBACK_POLICY
);
recorder!(
    record_packed_merge_split_fallback_prefix,
    PACKED_MERGE_SPLIT_FALLBACK_PREFIX
);
recorder!(
    record_packed_merge_split_fallback_width,
    PACKED_MERGE_SPLIT_FALLBACK_WIDTH
);
recorder!(
    record_packed_merge_split_transition_attempts,
    PACKED_MERGE_SPLIT_TRANSITION_ATTEMPTS
);
recorder!(
    record_packed_merge_split_transition_dead,
    PACKED_MERGE_SPLIT_TRANSITION_DEAD
);
recorder!(record_packed_dfa_queries, PACKED_DFA_QUERIES);
recorder!(
    record_packed_dfa_transition_hits,
    PACKED_DFA_TRANSITION_HITS
);
recorder!(
    record_packed_dfa_transition_misses,
    PACKED_DFA_TRANSITION_MISSES
);
recorder!(
    record_packed_dfa_states_interned,
    PACKED_DFA_STATES_INTERNED
);
recorder!(
    record_packed_dfa_source_rows_prepared,
    PACKED_DFA_SOURCE_ROWS_PREPARED
);
recorder!(
    record_packed_dfa_class_zero_probes,
    PACKED_DFA_CLASS_ZERO_PROBES
);
recorder!(
    record_packed_dfa_class_zero_reusable_probes,
    PACKED_DFA_CLASS_ZERO_REUSABLE_PROBES
);
recorder!(
    record_packed_dfa_physical_target_probes,
    PACKED_DFA_PHYSICAL_TARGET_PROBES
);
recorder!(record_generated_transition_hits, GENERATED_TRANSITION_HITS);
recorder!(
    record_generated_transition_misses,
    GENERATED_TRANSITION_MISSES
);
recorder!(
    record_generated_product_expansions,
    GENERATED_PRODUCT_EXPANSIONS
);
recorder!(
    record_generated_product_identity_expansions,
    GENERATED_PRODUCT_IDENTITY_EXPANSIONS
);
recorder!(
    record_generated_product_unique_expansions,
    GENERATED_PRODUCT_UNIQUE_EXPANSIONS
);
recorder!(
    record_generated_product_repeated_expansions,
    GENERATED_PRODUCT_REPEATED_EXPANSIONS
);
recorder!(record_epsilon_input_positions, EPSILON_INPUT_POSITIONS);
recorder!(record_epsilon_output_positions, EPSILON_OUTPUT_POSITIONS);
recorder!(record_characteristic_vectors, CHARACTERISTIC_VECTORS);
recorder!(record_characteristic_units, CHARACTERISTIC_UNITS);
recorder!(record_successor_candidates, SUCCESSOR_CANDIDATES);
recorder!(record_state_insert_attempts, STATE_INSERT_ATTEMPTS);
recorder!(record_state_insert_retained, STATE_INSERT_RETAINED);
recorder!(record_subsumption_checks, SUBSUMPTION_CHECKS);
recorder!(record_state_copy_calls, STATE_COPY_CALLS);
recorder!(record_state_positions_copied, STATE_POSITIONS_COPIED);
recorder!(record_state_bytes_copied, STATE_BYTES_COPIED);
recorder!(record_state_positions_enqueued, STATE_POSITIONS_ENQUEUED);
recorder!(record_state_bytes_enqueued, STATE_BYTES_ENQUEUED);
recorder!(record_pool_acquires, POOL_ACQUIRES);
recorder!(record_pool_reuses, POOL_REUSES);
recorder!(record_pool_misses, POOL_MISSES);
recorder!(record_pool_releases, POOL_RELEASES);
recorder!(record_matches_materialized, MATCHES_MATERIALIZED);
recorder!(record_parent_path_queries, PARENT_PATH_QUERIES);
recorder!(record_cursor_key_queries, CURSOR_KEY_QUERIES);
recorder!(record_path_arena_nodes_created, PATH_ARENA_NODES_CREATED);
recorder!(
    record_cursor_key_reconstructions,
    CURSOR_KEY_RECONSTRUCTIONS
);
recorder!(record_cursor_key_reverse_steps, CURSOR_KEY_REVERSE_STEPS);
recorder!(record_term_units_materialized, TERM_UNITS_MATERIALIZED);
recorder!(record_dfs_nodes_paged, DFS_NODES_PAGED);
recorder!(record_dfs_nodes_eager, DFS_NODES_EAGER);
recorder!(record_dfs_edge_page_requests, DFS_EDGE_PAGE_REQUESTS);
recorder!(record_dfs_edges_fetched, DFS_EDGES_FETCHED);
recorder!(record_dfs_edges_consumed, DFS_EDGES_CONSUMED);
recorder!(record_dfs_edge_buffer_spills, DFS_EDGE_BUFFER_SPILLS);
recorder!(
    record_foreign_is_final_callbacks,
    FOREIGN_IS_FINAL_CALLBACKS
);
recorder!(record_foreign_edge_callbacks, FOREIGN_EDGE_CALLBACKS);
recorder!(record_foreign_edge_pages, FOREIGN_EDGE_PAGES);
recorder!(record_foreign_edge_descriptors, FOREIGN_EDGE_DESCRIPTORS);
recorder!(record_foreign_node_cache_hits, FOREIGN_NODE_CACHE_HITS);
recorder!(record_foreign_node_cache_misses, FOREIGN_NODE_CACHE_MISSES);
recorder!(
    record_foreign_pending_cursors_emitted,
    FOREIGN_PENDING_CURSORS_EMITTED
);
recorder!(
    record_foreign_ready_cursors_emitted,
    FOREIGN_READY_CURSORS_EMITTED
);
recorder!(
    record_foreign_edge_cursor_promotions,
    FOREIGN_EDGE_CURSOR_PROMOTIONS
);
recorder!(
    record_foreign_pending_descriptor_loads,
    FOREIGN_PENDING_DESCRIPTOR_LOADS
);
recorder!(
    record_foreign_ready_descriptor_reads,
    FOREIGN_READY_DESCRIPTOR_READS
);
recorder!(
    record_foreign_child_directory_lookups,
    FOREIGN_CHILD_DIRECTORY_LOOKUPS
);
recorder!(record_foreign_leaf_expansions, FOREIGN_LEAF_EXPANSIONS);
recorder!(record_foreign_graph_decodes, FOREIGN_GRAPH_DECODES);
recorder!(record_ffi_matches_packed, FFI_MATCHES_PACKED);
recorder!(record_ffi_bytes_packed, FFI_BYTES_PACKED);

#[inline(always)]
pub(crate) fn record_pending_queue_size(size: usize) {
    #[cfg(feature = "perf-instrumentation")]
    PENDING_QUEUE_PEAK.fetch_max(size as u64, Ordering::Relaxed);
    #[cfg(not(feature = "perf-instrumentation"))]
    let _ = size;
}

#[inline(always)]
pub(crate) fn record_dfs_edge_buffer_size(size: usize) {
    #[cfg(feature = "perf-instrumentation")]
    DFS_EDGE_BUFFER_PEAK.fetch_max(size as u64, Ordering::Relaxed);
    #[cfg(not(feature = "perf-instrumentation"))]
    let _ = size;
}

/// Reset all causal counters to zero.
#[cfg(feature = "perf-instrumentation")]
pub fn reset_causal_perf_stats() {
    for counter in counters() {
        counter.store(0, Ordering::Relaxed);
    }
}

/// No-op reset for timing/profile builds where counters are compiled out.
#[cfg(not(feature = "perf-instrumentation"))]
pub fn reset_causal_perf_stats() {}

/// Snapshot all causal counters.
#[cfg(feature = "perf-instrumentation")]
pub fn causal_perf_stats() -> CausalPerfStats {
    let load = |counter: &AtomicU64| counter.load(Ordering::Relaxed);
    CausalPerfStats {
        dictionary_intersections: load(&DICTIONARY_INTERSECTIONS),
        owned_traversal_arena_insertions: load(&OWNED_TRAVERSAL_ARENA_INSERTIONS),
        final_checks: load(&FINAL_CHECKS),
        edges_enumerated: load(&EDGES_ENUMERATED),
        transition_attempts: load(&TRANSITION_ATTEMPTS),
        transition_accepted: load(&TRANSITION_ACCEPTED),
        packed_standard_queries: load(&PACKED_STANDARD_QUERIES),
        positional_unit_queries: load(&POSITIONAL_UNIT_QUERIES),
        packed_standard_transition_attempts: load(&PACKED_STANDARD_TRANSITION_ATTEMPTS),
        packed_standard_transition_dead: load(&PACKED_STANDARD_TRANSITION_DEAD),
        packed_osa_queries: load(&PACKED_OSA_QUERIES),
        packed_osa_fallback_policy: load(&PACKED_OSA_FALLBACK_POLICY),
        packed_osa_fallback_prefix: load(&PACKED_OSA_FALLBACK_PREFIX),
        packed_osa_fallback_width: load(&PACKED_OSA_FALLBACK_WIDTH),
        packed_osa_transition_attempts: load(&PACKED_OSA_TRANSITION_ATTEMPTS),
        packed_osa_transition_dead: load(&PACKED_OSA_TRANSITION_DEAD),
        packed_merge_split_queries: load(&PACKED_MERGE_SPLIT_QUERIES),
        packed_merge_split_fallback_policy: load(&PACKED_MERGE_SPLIT_FALLBACK_POLICY),
        packed_merge_split_fallback_prefix: load(&PACKED_MERGE_SPLIT_FALLBACK_PREFIX),
        packed_merge_split_fallback_width: load(&PACKED_MERGE_SPLIT_FALLBACK_WIDTH),
        packed_merge_split_transition_attempts: load(&PACKED_MERGE_SPLIT_TRANSITION_ATTEMPTS),
        packed_merge_split_transition_dead: load(&PACKED_MERGE_SPLIT_TRANSITION_DEAD),
        packed_dfa_queries: load(&PACKED_DFA_QUERIES),
        packed_dfa_transition_hits: load(&PACKED_DFA_TRANSITION_HITS),
        packed_dfa_transition_misses: load(&PACKED_DFA_TRANSITION_MISSES),
        packed_dfa_states_interned: load(&PACKED_DFA_STATES_INTERNED),
        packed_dfa_source_rows_prepared: load(&PACKED_DFA_SOURCE_ROWS_PREPARED),
        packed_dfa_class_zero_probes: load(&PACKED_DFA_CLASS_ZERO_PROBES),
        packed_dfa_class_zero_reusable_probes: load(&PACKED_DFA_CLASS_ZERO_REUSABLE_PROBES),
        packed_dfa_physical_target_probes: load(&PACKED_DFA_PHYSICAL_TARGET_PROBES),
        generated_transition_hits: load(&GENERATED_TRANSITION_HITS),
        generated_transition_misses: load(&GENERATED_TRANSITION_MISSES),
        generated_product_expansions: load(&GENERATED_PRODUCT_EXPANSIONS),
        generated_product_identity_expansions: load(&GENERATED_PRODUCT_IDENTITY_EXPANSIONS),
        generated_product_unique_expansions: load(&GENERATED_PRODUCT_UNIQUE_EXPANSIONS),
        generated_product_repeated_expansions: load(&GENERATED_PRODUCT_REPEATED_EXPANSIONS),
        epsilon_input_positions: load(&EPSILON_INPUT_POSITIONS),
        epsilon_output_positions: load(&EPSILON_OUTPUT_POSITIONS),
        characteristic_vectors: load(&CHARACTERISTIC_VECTORS),
        characteristic_units: load(&CHARACTERISTIC_UNITS),
        successor_candidates: load(&SUCCESSOR_CANDIDATES),
        state_insert_attempts: load(&STATE_INSERT_ATTEMPTS),
        state_insert_retained: load(&STATE_INSERT_RETAINED),
        subsumption_checks: load(&SUBSUMPTION_CHECKS),
        state_copy_calls: load(&STATE_COPY_CALLS),
        state_positions_copied: load(&STATE_POSITIONS_COPIED),
        state_bytes_copied: load(&STATE_BYTES_COPIED),
        state_positions_enqueued: load(&STATE_POSITIONS_ENQUEUED),
        state_bytes_enqueued: load(&STATE_BYTES_ENQUEUED),
        pending_queue_peak: load(&PENDING_QUEUE_PEAK),
        pool_acquires: load(&POOL_ACQUIRES),
        pool_reuses: load(&POOL_REUSES),
        pool_misses: load(&POOL_MISSES),
        pool_releases: load(&POOL_RELEASES),
        matches_materialized: load(&MATCHES_MATERIALIZED),
        parent_path_queries: load(&PARENT_PATH_QUERIES),
        cursor_key_queries: load(&CURSOR_KEY_QUERIES),
        path_arena_nodes_created: load(&PATH_ARENA_NODES_CREATED),
        cursor_key_reconstructions: load(&CURSOR_KEY_RECONSTRUCTIONS),
        cursor_key_reverse_steps: load(&CURSOR_KEY_REVERSE_STEPS),
        term_units_materialized: load(&TERM_UNITS_MATERIALIZED),
        dfs_nodes_paged: load(&DFS_NODES_PAGED),
        dfs_nodes_eager: load(&DFS_NODES_EAGER),
        dfs_edge_page_requests: load(&DFS_EDGE_PAGE_REQUESTS),
        dfs_edges_fetched: load(&DFS_EDGES_FETCHED),
        dfs_edges_consumed: load(&DFS_EDGES_CONSUMED),
        dfs_edge_buffer_peak: load(&DFS_EDGE_BUFFER_PEAK),
        dfs_edge_buffer_spills: load(&DFS_EDGE_BUFFER_SPILLS),
        foreign_is_final_callbacks: load(&FOREIGN_IS_FINAL_CALLBACKS),
        foreign_edge_callbacks: load(&FOREIGN_EDGE_CALLBACKS),
        foreign_edge_pages: load(&FOREIGN_EDGE_PAGES),
        foreign_edge_descriptors: load(&FOREIGN_EDGE_DESCRIPTORS),
        foreign_node_cache_hits: load(&FOREIGN_NODE_CACHE_HITS),
        foreign_node_cache_misses: load(&FOREIGN_NODE_CACHE_MISSES),
        foreign_pending_cursors_emitted: load(&FOREIGN_PENDING_CURSORS_EMITTED),
        foreign_ready_cursors_emitted: load(&FOREIGN_READY_CURSORS_EMITTED),
        foreign_edge_cursor_promotions: load(&FOREIGN_EDGE_CURSOR_PROMOTIONS),
        foreign_pending_descriptor_loads: load(&FOREIGN_PENDING_DESCRIPTOR_LOADS),
        foreign_ready_descriptor_reads: load(&FOREIGN_READY_DESCRIPTOR_READS),
        foreign_child_directory_lookups: load(&FOREIGN_CHILD_DIRECTORY_LOOKUPS),
        foreign_leaf_expansions: load(&FOREIGN_LEAF_EXPANSIONS),
        foreign_graph_decodes: load(&FOREIGN_GRAPH_DECODES),
        ffi_matches_packed: load(&FFI_MATCHES_PACKED),
        ffi_bytes_packed: load(&FFI_BYTES_PACKED),
    }
}

/// Return an all-zero snapshot when instrumentation is compiled out.
#[cfg(not(feature = "perf-instrumentation"))]
pub fn causal_perf_stats() -> CausalPerfStats {
    CausalPerfStats::default()
}

#[cfg(feature = "perf-instrumentation")]
fn counters() -> [&'static AtomicU64; 84] {
    [
        &DICTIONARY_INTERSECTIONS,
        &OWNED_TRAVERSAL_ARENA_INSERTIONS,
        &FINAL_CHECKS,
        &EDGES_ENUMERATED,
        &TRANSITION_ATTEMPTS,
        &TRANSITION_ACCEPTED,
        &PACKED_STANDARD_QUERIES,
        &POSITIONAL_UNIT_QUERIES,
        &PACKED_STANDARD_TRANSITION_ATTEMPTS,
        &PACKED_STANDARD_TRANSITION_DEAD,
        &PACKED_OSA_QUERIES,
        &PACKED_OSA_FALLBACK_POLICY,
        &PACKED_OSA_FALLBACK_PREFIX,
        &PACKED_OSA_FALLBACK_WIDTH,
        &PACKED_OSA_TRANSITION_ATTEMPTS,
        &PACKED_OSA_TRANSITION_DEAD,
        &PACKED_MERGE_SPLIT_QUERIES,
        &PACKED_MERGE_SPLIT_FALLBACK_POLICY,
        &PACKED_MERGE_SPLIT_FALLBACK_PREFIX,
        &PACKED_MERGE_SPLIT_FALLBACK_WIDTH,
        &PACKED_MERGE_SPLIT_TRANSITION_ATTEMPTS,
        &PACKED_MERGE_SPLIT_TRANSITION_DEAD,
        &PACKED_DFA_QUERIES,
        &PACKED_DFA_TRANSITION_HITS,
        &PACKED_DFA_TRANSITION_MISSES,
        &PACKED_DFA_STATES_INTERNED,
        &PACKED_DFA_SOURCE_ROWS_PREPARED,
        &PACKED_DFA_CLASS_ZERO_PROBES,
        &PACKED_DFA_CLASS_ZERO_REUSABLE_PROBES,
        &PACKED_DFA_PHYSICAL_TARGET_PROBES,
        &GENERATED_TRANSITION_HITS,
        &GENERATED_TRANSITION_MISSES,
        &GENERATED_PRODUCT_EXPANSIONS,
        &GENERATED_PRODUCT_IDENTITY_EXPANSIONS,
        &GENERATED_PRODUCT_UNIQUE_EXPANSIONS,
        &GENERATED_PRODUCT_REPEATED_EXPANSIONS,
        &EPSILON_INPUT_POSITIONS,
        &EPSILON_OUTPUT_POSITIONS,
        &CHARACTERISTIC_VECTORS,
        &CHARACTERISTIC_UNITS,
        &SUCCESSOR_CANDIDATES,
        &STATE_INSERT_ATTEMPTS,
        &STATE_INSERT_RETAINED,
        &SUBSUMPTION_CHECKS,
        &STATE_COPY_CALLS,
        &STATE_POSITIONS_COPIED,
        &STATE_BYTES_COPIED,
        &STATE_POSITIONS_ENQUEUED,
        &STATE_BYTES_ENQUEUED,
        &PENDING_QUEUE_PEAK,
        &POOL_ACQUIRES,
        &POOL_REUSES,
        &POOL_MISSES,
        &POOL_RELEASES,
        &MATCHES_MATERIALIZED,
        &PARENT_PATH_QUERIES,
        &CURSOR_KEY_QUERIES,
        &PATH_ARENA_NODES_CREATED,
        &CURSOR_KEY_RECONSTRUCTIONS,
        &CURSOR_KEY_REVERSE_STEPS,
        &TERM_UNITS_MATERIALIZED,
        &DFS_NODES_PAGED,
        &DFS_NODES_EAGER,
        &DFS_EDGE_PAGE_REQUESTS,
        &DFS_EDGES_FETCHED,
        &DFS_EDGES_CONSUMED,
        &DFS_EDGE_BUFFER_PEAK,
        &DFS_EDGE_BUFFER_SPILLS,
        &FOREIGN_IS_FINAL_CALLBACKS,
        &FOREIGN_EDGE_CALLBACKS,
        &FOREIGN_EDGE_PAGES,
        &FOREIGN_EDGE_DESCRIPTORS,
        &FOREIGN_NODE_CACHE_HITS,
        &FOREIGN_NODE_CACHE_MISSES,
        &FOREIGN_PENDING_CURSORS_EMITTED,
        &FOREIGN_READY_CURSORS_EMITTED,
        &FOREIGN_EDGE_CURSOR_PROMOTIONS,
        &FOREIGN_PENDING_DESCRIPTOR_LOADS,
        &FOREIGN_READY_DESCRIPTOR_READS,
        &FOREIGN_CHILD_DIRECTORY_LOOKUPS,
        &FOREIGN_LEAF_EXPANSIONS,
        &FOREIGN_GRAPH_DECODES,
        &FFI_MATCHES_PACKED,
        &FFI_BYTES_PACKED,
    ]
}
